version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-library-service-app
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    links:
      - db
    volumes:
      - app:/var/lib/app/data
      - .:/home/app
      - /home/app/node_modules
    restart: always
    networks:
      - home-lib-network
    command: npm run start:migration:dev
  db:
    build:
      context: .
      dockerfile: ./src/db/Dockerfile
    container_name: home-library-service-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    networks:
      - home-lib-network
volumes:
  app:
  db:
networks:
  home-lib-network:
    name: home-lib-network
    driver: bridge
